# Generated by Django 3.2.8 on 2021-10-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseId', models.AutoField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('pupilId', models.AutoField(primary_key=True, serialize=False)),
                ('pupilName', models.CharField(max_length=255)),
                ('std', models.CharField(max_length=50)),
                ('posted_date', models.DateTimeField()),
            ],
        ),
    ]
