# Generated by Django 3.2.8 on 2021-10-28 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_courses_pupil'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
