# Generated by Django 3.2.8 on 2021-10-28 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_courses_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pupil',
        ),
        migrations.AddField(
            model_name='courses',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
