# Generated by Django 3.2.8 on 2021-10-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211028_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='posted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
