# Generated by Django 3.2.8 on 2021-10-28 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
